
import { test, expect } from '@playwright/test';

test.describe('Manual Master Data Entry Simulation', () => {
    test.setTimeout(600000); // 10 minutes

    test.beforeEach(async ({ page }) => {
        // Login Logic
        await page.goto('/login');
        const emailInput = page.locator('input[name="email"]');
        if (await emailInput.count() > 0) {
            await emailInput.fill('s.o.02.0999@gmail.com');
            await page.click('button:has-text("Development Login")');
        } else {
            // Check for direct button
            if (await page.isVisible('button:has-text("Development Login")')) {
                await page.click('button:has-text("Development Login")');
            } else {
                // May need to verify if already logged in or diff provider
                await page.click('text=Development Login');
                await page.waitForSelector('input[name="email"]');
                await page.fill('input[name="email"]', 's.o.02.0999@gmail.com');
                await page.click('button:has-text("Development Login")');
            }
        }
        await page.waitForTimeout(2000);
        await page.goto('/');
    });

    // 1. Clients (15)
    test('UI: Create 15 Clients', async ({ page }) => {
        for (let i = 1; i <= 15; i++) {
            await page.goto('/clients');
            await page.click('button:has-text("新規登録")');
            await page.waitForSelector('text=新規クライアント登録');

            await page.fill('input[placeholder="株式会社〇〇"]', `Manual Client ${i}`);
            await page.fill('input[placeholder="山田 太郎"]', `Contact ${i}`);
            await page.fill('input[placeholder="example@email.com"]', `manual_client_${i}@example.com`);

            await page.click('button:has-text("保存")');
            // Wait for modal to close or toast
            await page.waitForTimeout(500);
            // await expect(page.locator(`text=Manual Client ${i}`).first()).toBeVisible();
        }
    });

    // 2. Partners (20)
    test('UI: Create 20 Partners', async ({ page }) => {
        for (let i = 1; i <= 20; i++) {
            await page.goto('/partners');
            await page.click('button:has-text("パートナー登録")');
            await page.waitForSelector('text=新規パートナー登録');

            await page.fill('input[placeholder="山田 太郎"]', `Manual Partner ${i}`);
            await page.fill('input[placeholder="example@email.com"]', `manual_partner_${i}@example.com`);

            // Check role if available? Assuming first checkbox
            // Or just save (role is optional-ish or has defaults)
            if (await page.isVisible('button:has-text("保存")')) {
                await page.click('button:has-text("保存")');
            }
            await page.waitForTimeout(500);
        }
    });

    // 3. Rules (30)
    test('UI: Create 30 Pricing Rules', async ({ page }) => {
        for (let i = 1; i <= 30; i++) {
            await page.goto('/pricing-rules');
            await page.click('button:has-text("+ ルール追加")');
            await page.waitForSelector('text=新規ルール作成');

            await page.fill('input[placeholder="例: 標準撮影費用"]', `Manual Rule ${i}`);
            await page.fill('input[placeholder="ルールの詳細説明"]', `Generated by Manual Sim ${i}`);

            // Fill Price and Cost
            const priceInput = page.locator('div').filter({ hasText: '売上単価 (円)' }).locator('input[type="number"]');
            await priceInput.fill('20000');

            const costInput = page.locator('div').filter({ hasText: '原価単価 (円)' }).locator('input[type="number"]');
            await costInput.fill('10000');

            await page.click('button:has-text("保存")');
            await page.waitForTimeout(500);
        }
    });

});
