
import { test, expect } from '@playwright/test';

test.describe('Bulk Data Generation', () => {
    test.setTimeout(300000); // 5 minutes timeout

    // Login before all tests
    test.beforeEach(async ({ page }) => {
        // 1. Go to login
        await page.goto('/login');

        // 2. Click "Sign in with Development Login" (Credentials provider)
        // The button might just say "Sign in with Development Login" or be part of a list
        // We look for the button that submits credentials

        // If multiple providers, NextAuth usually shows a list.
        // Credentials provider usually has inputs on the main page if customized, 
        // OR a button "Sign in with Development Login" which leads to inputs.
        // Let's assume standard NextAuth UI for now or just generic form filling if visible.

        // Check if we are on the provider selection page or direct login
        // If inputs are visible (email), fill them.
        const emailInput = page.locator('input[name="email"]');
        if (await emailInput.count() > 0) {
            await emailInput.fill('s.o.02.0999@gmail.com');
            // If there is a password field, we might need to fill dummy, but our verify says only email.
            // There might be a "Sign In with Email" button.
            await page.click('button:has-text("Development Login")');
        } else {
            // Maybe we need to click the provider button first
            await page.click('text=Development Login');
            await page.waitForSelector('input[name="email"]');
            await page.fill('input[name="email"]', 's.o.02.0999@gmail.com');
            await page.click('button:has-text("Development Login")');
        }

        // Wait for connection or potential redirect
        await page.waitForTimeout(2000);

        // Force navigation to dashboard
        await page.goto('/');

        // Wait for dashboard
        await expect(page).toHaveURL('/');
    });

    test('Register 10 Clients', async ({ page }) => {
        for (let i = 1; i <= 10; i++) {
            await page.goto('/clients');
            await page.click('button:has-text("新規登録")');

            // Wait for modal
            await page.waitForSelector('text=新規クライアント登録');

            // Use placeholder selector
            await page.fill('input[placeholder="株式会社〇〇"]', `Auto Client ${i}`); // Name
            await page.fill('input[placeholder="山田 太郎"]', `Contact ${i}`); // Contact Person
            await page.fill('input[placeholder="example@email.com"]', `client${i}@example.com`);

            // Screenshot form
            await page.screenshot({ path: `test-results/client-${i}-form.png` });

            // Save
            await page.click('button:has-text("保存")');

            // Wait for success (modal closes or item appears)
            await expect(page.locator(`text=Auto Client ${i}`).first()).toBeVisible();
            await page.waitForTimeout(500); // Small pause
        }
    });

    test('Register 10 Partners', async ({ page }) => {
        for (let i = 1; i <= 10; i++) {
            await page.goto('/partners');
            await page.click('button:has-text("パートナー登録")');

            await page.waitForSelector('text=新規パートナー登録');

            await page.fill('input[placeholder="山田 太郎"]', `Auto Partner ${i}`);
            await page.fill('input[placeholder="example@email.com"]', `partner${i}@example.com`);

            // Role selection (checkboxes) - Optional for basic test, defaults to none or manual
            // Check "カメラマン"
            await page.click('label:has-text("カメラマン")');

            await page.click('button:has-text("保存")');

            await expect(page.locator(`text=Auto Partner ${i}`).first()).toBeVisible();
            await page.waitForTimeout(500);
        }
    });

    test('Register 20 Pricing Rules', async ({ page }) => {
        for (let i = 1; i <= 20; i++) {
            await page.goto('/pricing-rules');
            await page.click('button:has-text("+ ルール追加")');

            await page.waitForSelector('text=新規ルール作成');

            await page.fill('input[placeholder="例: 標準撮影費用"]', `Auto Rule ${i}`);
            await page.fill('input[placeholder="ルールの詳細説明"]', `Generated by E2E`);

            // Pricing Type is FIXED by default.
            // Fill Fixed Price and Cost
            // Use locator filter
            const priceInput = page.locator('div').filter({ hasText: '売上単価 (円)' }).locator('input[type="number"]');
            await priceInput.fill('10000');

            const costInput = page.locator('div').filter({ hasText: '原価単価 (円)' }).locator('input[type="number"]');
            await costInput.fill('5000');

            await page.click('button:has-text("保存")');

            await expect(page.locator(`text=Auto Rule ${i}`).first()).toBeVisible();
            await page.waitForTimeout(500);
        }
    });

    test('Register 50 Invoices and Process Layout', async ({ page }) => {
        // We need 50 invoices.
        // 10 Draft
        // 35 Delivered
        // 5 Paid

        for (let i = 1; i <= 50; i++) {
            console.log(`Creating Invoice ${i}...`);
            await page.goto('/invoices/new'); // Assuming this route exists

            // Step 1: Basic Info
            // Select Client (Dropdown)
            await page.click('text=クライアントを選択'); // Trigger select
            // Select random client? Or just first.
            await page.click('text=Auto Client 1'); // Use the first one for simplicity

            // Subject / Title
            await page.fill('input[name="title"]', `Auto Project ${i}`);

            // Save Draft (Step 1)
            await page.click('button:has-text("下書き保存")');

            // Check if created
            // Should redirect to edit or list.
            // Assume redirect to Edit page.

            // If we want to process it further:
            if (i > 10) {
                // Move to next steps?
                // Need to know how status flow works.
                // If "Delivered", we likely need to Add Items -> Mark as Delivered.

                // Add Item
                await page.click('text=品目を追加');
                await page.fill('input[name="itemName"]', 'Video Production');
                await page.fill('input[name="price"]', '100000');
                await page.click('button:has-text("保存")'); // Save item

                // Workflow: Click "受注確定" (Order Confirmed) -> "制作中" -> "納品"
                // Assuming buttons exist
                if (await page.isVisible('button:has-text("受注確定")')) {
                    await page.click('button:has-text("受注確定")');
                }
                if (await page.isVisible('button:has-text("制作開始")')) {
                    await page.click('button:has-text("制作開始")');
                }
                if (await page.isVisible('button:has-text("納品")')) {
                    await page.click('button:has-text("納品")');
                }

                // For last 5 (46-50), make PAID
                if (i > 45) {
                    if (await page.isVisible('button:has-text("請求書発行")')) {
                        await page.click('button:has-text("請求書発行")');
                    }
                    if (await page.isVisible('button:has-text("入金確認")')) {
                        await page.click('button:has-text("入金確認")');
                    }
                }
            }
        }
    });

});
